---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: check if ufw rule has been configured
      ansible.builtin.command: ufw status
      register: out
      changed_when: false
      failed_when: "'124/tcp                    ALLOW       123.123.123.123' not in out"
